name: 42_C_valid_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  norm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install 42-norminette
      run: 
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install --upgrade norminette

  check-compile-flags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install gcc and make
        run: sudo apt-get install -y gcc make
      
      - name: Run make
        run: make
